Unassign screen WorkAllocation 2
hmcts/rpx-xui-webapp pull request #1039
Opened 2021-05-07 09:00 UTC by kuda1992

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3596

### Change description ###

1. Mocked the node layer to return hard coded list of tasks.
2. Made changes to the unassign screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-05-07 13:51 UTC, connorpgpmcelroy commented on src/work-allocation-2/components/constants copy/index.ts
> +import { CONFIG_CONSTANTS as ConfigConstants } from './config.constants';
See comment above

2021-05-07 13:57 UTC, connorpgpmcelroy requested changes
PR is re-adding things I've previously removed because it branched off before I had pushed the changes so they need to be re-removed

2021-05-07 13:57 UTC, connorpgpmcelroy commented on src/work-allocation-2/components/task-field/task-field.component.scss
> +.xui-image-field__container {
Again, this file should not exist. This should be present in file called task-field.component.scss

2021-05-07 13:57 UTC, connorpgpmcelroy commented on src/work-allocation-2/containers/task-assignment/task-assignment-container.component.scss
> +.task-assignment-btn {
This styling does not affect anything and should not be added again - File should be removed from PR

2021-05-07 15:14 UTC, connorpgpmcelroy approved these changes
LGTM

2021-05-17 08:56 UTC, udaydenduluri33 approved these changes
LGTMk

2021-05-17 14:41 UTC, merged