Feature/e UI 4031
hmcts/rpx-xui-webapp pull request #1096
Opened 2021-05-27 14:35 UTC by udaydenduluri33

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-05-28 15:38 UTC, kuda1992 requested changes

2021-05-28 15:38 UTC, kuda1992 commented on src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
> +    this.isPaginationEnabled$.subscribe(enabled => {
Do we need to have nested subscribes here?. Can we utilise mergeMap. 
  `this.isPaginationEnabled$. pipe(mergeMap((enabled) => this. performSearchPagination() || this. performSearch()).subscribe()`

2021-05-28 15:38 UTC, kuda1992 commented on src/work-allocation/services/work-allocation-task.service.ts
> +  public searchTaskWithPagination(body: { searchRequest: SearchTaskRequest, view: string }): Observable<any> {
Can we specify the returned type?

2021-06-01 13:13 UTC, kuda1992 approved these changes
looks good

2021-06-01 13:19 UTC, leepavlouhmcts approved these changes

2021-06-03 10:48 UTC, merged