EUI 4002 screen width
hmcts/rpx-xui-webapp pull request #1113
Opened 2021-06-08 14:11 UTC by ishOsw

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4002

### Change description ###

Changes to the Manage cases screen width

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-06-09 09:13 UTC, leepavlouhmcts submitted a review, later dismissed

2021-06-09 09:15 UTC, paul-graham commented on src/app/containers/app/app.component.scss
> +  overflow-x:hidden;
What is the `overflow-x: hidden` for? If we've got content exceeding the bounds that we just clip, that's not ideal...

2021-06-09 09:35 UTC, paul-graham requested changes
No margin when I think there should be...
<img width="244" alt="Screenshot 2021-06-09 at 10 30 23" src="https://user-images.githubusercontent.com/73112256/121330709-2c9ace00-c90e-11eb-91f3-ae84ec6beb40.png">

The header doesn't behave like the content (this is scrolled to the right):
<img width="446" alt="Screenshot 2021-06-09 at 10 31 56" src="https://user-images.githubusercontent.com/73112256/121330779-391f2680-c90e-11eb-9561-85dcda69388e.png">

And nor does the footer:
<img width="305" alt="Screenshot 2021-06-09 at 10 32 32" src="https://user-images.githubusercontent.com/73112256/121330787-3a505380-c90e-11eb-9819-f1dc125bc742.png">

2021-06-14 09:04 UTC, leepavlouhmcts requested changes
on the cases page, the BETA text on the top left is out of alignment but is fine on the case details page. if this isnt because of this css fix then im hapy to approve

2021-06-14 09:28 UTC, leepavlouhmcts approved these changes

2021-06-14 09:31 UTC, paul-graham commented
> on the cases page, the BETA text on the top left is out of alignment but is fine on the case details page. if this isnt because of this css fix then im hapy to approve

I think the issue is that the **Case list** has additional padding... but it already had that. Just looked on AAT and it's the same.

2021-06-14 09:51 UTC, paul-graham commented
Some slightly odd behaviour when you go above 1920px...

Footer @ 1945px (looks fine up to 1920px):
<img width="276" alt="Footer 1945px" src="https://user-images.githubusercontent.com/73112256/121872178-e0300380-ccfc-11eb-83fd-97b591a23969.png">

Header @ 1860px:
<img width="266" alt="header 1860px" src="https://user-images.githubusercontent.com/73112256/121872185-e1613080-ccfc-11eb-96cd-4e882ac8a7d0.png">

Header @ 1920px:
<img width="265" alt="header 1920px" src="https://user-images.githubusercontent.com/73112256/121872186-e2925d80-ccfc-11eb-9968-36fcf7eb39e4.png">

Header @ 1979px:
<img width="273" alt="header 1979px" src="https://user-images.githubusercontent.com/73112256/121872187-e32af400-ccfc-11eb-897a-501a63ad0901.png">

Header @ 1980px:
<img width="280" alt="header 1980px" src="https://user-images.githubusercontent.com/73112256/121872188-e32af400-ccfc-11eb-992d-dcc61300638d.png">

Header (left) @ 1979px:
<img width="112" alt="header left 1979px" src="https://user-images.githubusercontent.com/73112256/121872189-e3c38a80-ccfc-11eb-8ed3-c4413f621821.png">

Header (left) @ 1980px:
<img width="142" alt="header left 1980px" src="https://user-images.githubusercontent.com/73112256/121872191-e3c38a80-ccfc-11eb-9a3d-58868ba8c1ee.png">

2021-06-14 09:52 UTC, paul-graham reviewed
Some odd behaviour when you get above 1920px and especially above 1980px. Not sure this is a blocker, though...

2021-06-16 09:06 UTC, paul-graham approved these changes
The CSS looks good and, running it locally, it all seems to behave itself nicely. 🙂

2021-06-16 09:08 UTC, leepavlouhmcts approved these changes

2021-08-02 14:23 UTC, Mo-Lala84 approved these changes
approved

2021-08-02 16:30 UTC, leepavlouhmcts approved these changes

2021-08-03 08:13 UTC, merged