WA pact tests updated to resolve data mismatch on provider side tests…
hmcts/rpx-xui-webapp pull request #1152
Opened 2021-06-30 13:01 UTC by sreekanthpuligadda

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4250 

### Change description ###
Updates to WA PACT tests,
Update to mutation test config. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2021-07-02 09:01 UTC, phillip-whitaker requested changes
A couple of comments

2021-07-02 09:01 UTC, phillip-whitaker commented on api/test/pact/pact-tests/settings/provider.mock.ts
> +      log: path.resolve(process.cwd(), "api/test/pact/logs", config.provider+".log"),
Are you not missing a double quote at the start of config.provider ?

2021-07-02 09:01 UTC, phillip-whitaker commented on api/test/pact/pact-tests/settings/provider.mock.ts
> +      log: path.resolve(process.cwd(), "api/test/pact/logs", config.provider+".log"),
Also, other parts of the project use single quotes. Should be consistent.

2021-07-02 09:01 UTC, phillip-whitaker commented on stryker.node.conf.js
> +
remove blank space

2021-07-02 09:09 UTC, phillip-whitaker commented on api/test/pact/pact-tests/settings/provider.mock.ts
> +      log: path.resolve(process.cwd(), "api/test/pact/logs", config.provider+".log"),
Just seen what is going on here - please use string interpolation instead

```suggestion
      log: path.resolve(process.cwd(), "api/test/pact/logs", `${config.provider}.log`),
```

2021-07-02 16:33 UTC, Vamshi-Muniganti approved these changes
looks fine to me

2021-07-05 08:17 UTC, udaydenduluri33 commented on api/test/pact/pact-tests/settings/provider.mock.ts
> +      log: path.resolve(process.cwd(), "api/test/pact/logs", config.provider+".log"),
@phillip-whitaker is no longer in the team. And I can see that its addressed

2021-07-05 08:21 UTC, udaydenduluri33 approved these changes
I can see that PACTS are now running which itself means that this code changes are working. @sreekanthpuligadda  LGTMs

2021-07-05 08:41 UTC, Mo-Lala84 approved these changes
approved now pact tests now resolving the mismatch

2021-07-05 09:00 UTC, merged