EUI-4112-cve-fix
hmcts/rpx-xui-webapp pull request #1168
Opened 2021-07-14 11:33 UTC by ishOsw

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4112

### Change description ###
Updating ccd-toolkit version

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-07-14 14:31 UTC, paul-graham reviewed
Is this for testing purposes or with the intention of merging into MC `master`? If the latter, it needs to be pointing at a fully released version of the toolkit, not one with a pre-release suffix... 🤔

2021-07-16 14:22 UTC, paul-graham requested changes
Two versions of the toolkit specified in `package.json`.

2021-07-16 14:22 UTC, paul-graham commented on package.json
>      "@hmcts/ccd-case-ui-toolkit": "4.1.0-rc.13",
There are two entries in here for the same thing... 🤔

2021-07-16 14:49 UTC, paul-graham reviewed
This will need a fully-released version of the CCD Case UI Toolkit... but otherwise, it's fine.

2021-08-19 08:58 UTC, Mo-Lala84 approved these changes
approved

2021-08-19 09:00 UTC, RiteshHMCTS submitted a review, later dismissed
Approved

2021-08-27 08:51 UTC, Mo-Lala84 submitted a review, later dismissed
approved

2021-08-27 08:54 UTC, udaydenduluri33 submitted a review, later dismissed
@ishOsw  @Mo-Lala84  I can see the upgraded CCD-UI toolkit library

2021-11-10 16:01 UTC, kuda1992 approved these changes
Approved with minor code improvement

2021-11-11 10:57 UTC, merged