4.3.0-rc.1
hmcts/rpx-xui-webapp pull request #1208
Opened 2021-07-27 20:11 UTC by rayliangatos

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###
Requested create a Toolkit RC release version 4.3.0-rc.1

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
[x] Not sure
```

2021-07-27 20:29 UTC, rayliangatos commented on src/app/services/ccd-config/ccd-case.config.ts
> +  }
DON'T approve and merge until you know these two exact values, this is just for get a build pipeline run successfully and release to preview for service testing.

2021-07-28 10:09 UTC, Mo-Lala84 approved these changes

2021-07-28 10:10 UTC, Mo-Lala84 requested changes
we need rc 2 version updating

2021-07-29 09:09 UTC, Mo-Lala84 approved these changes
approved

2021-07-29 09:12 UTC, RiteshHMCTS submitted a review, later dismissed

2021-08-11 08:43 UTC, Mo-Lala84 submitted a review, later dismissed
approved

2021-08-11 08:45 UTC, leepavlouhmcts submitted a review, later dismissed

2021-08-11 08:53 UTC, udaydenduluri33 commented on yarn.lock
> +"@hmcts/ccd-case-ui-toolkit@4.3.0-rc.15":
Version of CCDUI toolkit should be full version @Mo-Lala84

2021-08-11 10:17 UTC, udaydenduluri33 approved these changes

2021-08-12 08:41 UTC, RiteshHMCTS approved these changes
approved

2021-08-12 08:42 UTC, adnanakgun approved these changes

2021-08-12 13:01 UTC, merged