Feature/e UI 3818 duration access
hmcts/rpx-xui-webapp pull request #1223
Opened 2021-08-04 14:33 UTC by udaydenduluri33

https://tools.hmcts.net/jira/browse/EUI-3818
https://tools.hmcts.net/jira/browse/EUI-3819
https://tools.hmcts.net/jira/browse/EUI-3961
https://tools.hmcts.net/jira/browse/EUI-3864
https://tools.hmcts.net/jira/browse/EUI-3866

### Change description ###

Display User story - Roles and Access Tab

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-08-04 15:08 UTC, connorpgpmcelroy approved these changes
All looks good to me. Could add test based on display of radio buttons but do not think it's necessary

2021-08-10 13:54 UTC, kuda1992 requested changes
All good apart from little minor changes

2021-08-10 13:54 UTC, kuda1992 commented on src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
> +  public getEndDate() {
**Minor**  missing return type

2021-08-10 13:54 UTC, kuda1992 commented on src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
> +  public getStartDate() {
**Minor**  missing return type

2021-08-10 13:54 UTC, kuda1992 commented on src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
> +  public getTodayDate() {
**Minor**  missing return type

2021-08-10 13:54 UTC, kuda1992 commented on src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
> +  public onItemChange(item: DurationOfRole) {
**Minor**  missing return type

2021-08-10 14:01 UTC, udaydenduluri33 commented on src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
> +  public onItemChange(item: DurationOfRole) {
Done

2021-08-10 14:01 UTC, udaydenduluri33 commented on src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
> +  public getTodayDate() {
Done

2021-08-10 14:01 UTC, udaydenduluri33 commented on src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
> +  public getStartDate() {
Done

2021-08-10 14:57 UTC, kuda1992 approved these changes
All good

2021-08-10 14:58 UTC, merged