allocate link directive
hmcts/rpx-xui-webapp pull request #1244
Opened 2021-08-16 08:00 UTC by kuda1992

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3799?filter=-1

### Change description ###
Created a new endpoint which takes the caseId and checks if the user can allocate a role

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2021-08-16 08:39 UTC, udaydenduluri33 commented on api/workAllocation2/roleService.ts
> +export function handleShowAllocatorLinkByCaseId(caseId: string, req: EnhancedRequest): boolean {
@kuda1992  I can see you looking for caseId below. But, you also need to look if the the user has the case allocator role. That is missing. Could you please add it? Thanks

2021-08-16 08:43 UTC, rayliangatos commented on api/workAllocation2/interfaces/caseRole.ts
> +  LEAD_JUDGE = 'Lead Judge',
there has been a similar TypeOfRole in src\role-access\models\allocate-role.enum

2021-08-16 08:50 UTC, connorpgpmcelroy requested changes
Further to Uday's comment, would prefer legalops and judiciary in a constants/enum file

2021-08-16 08:50 UTC, connorpgpmcelroy commented on src/cases/directives/show-allocate-link.directive.ts
> +    if (!showAllocateRoleLink || userType === 'legalOps' && ShowAllocateLinkDirective.hasExceededNumberCaseManagerRoles(roles)) {
'legalOps' should be a constant/enum along with 'judiciary' so if we need to change any mention of it, looking through code is not necessary

2021-08-16 10:02 UTC, udaydenduluri33 commented on src/cases/directives/show-allocate-link.directive.ts
> +import { TypeOfRole } from 'src/role-access/models';
please move src to relative path

2021-08-16 10:03 UTC, udaydenduluri33 commented on src/cases/components/roles-and-access/roles-and-access.component.ts
>  import { LocationInfo } from 'src/app/store/reducers/app-config.reducer';
please move src to relative path

2021-08-16 10:03 UTC, udaydenduluri33 commented on src/cases/directives/show-allocate-link.directive.spec.ts
> +import { TypeOfRole } from 'src/role-access/models';
please move src to relative path

2021-08-16 10:03 UTC, udaydenduluri33 commented on src/cases/resolvers/case-roles-resolver.service.spec.ts
> +import { TypeOfRole } from 'src/role-access/models';
please move src to relative path

2021-08-16 14:35 UTC, connorpgpmcelroy requested changes
Minor changes required

2021-08-16 14:35 UTC, connorpgpmcelroy commented on api/workAllocation2/constants/roles.mock.data.ts
> +import { TypeOfRole } from '../../../src/role-access/models';
import contains 'src'

2021-08-16 14:35 UTC, connorpgpmcelroy commented on api/workAllocation2/util.ts
> +  return authorisations.some(authorisation => authorisation === 'case-allocator-role');
Think 'case-allocator-role' may already be a constant within the application so we should use that

2021-08-16 14:35 UTC, connorpgpmcelroy commented on src/role-access/components/case-roles-table/case-roles-table.component.html
> +      There are no {{userType === 'legalOps' ? 'legal ops' : userType }} roles for this case.
Could we not use the enum here?

2021-08-16 14:38 UTC, connorpgpmcelroy commented on api/workAllocation2/util.ts
> +  return authorisations.some(authorisation => authorisation === 'case-allocator-role');
checked and it's a constant in app.constants.ts

2021-08-16 14:39 UTC, connorpgpmcelroy commented on api/workAllocation2/util.ts
> +  return authorisations.some(authorisation => authorisation === 'case-allocator-role');
and also in api/user/constants.ts

2021-08-17 08:15 UTC, udaydenduluri33 approved these changes
Approving after the changes requested

2021-08-17 08:16 UTC, connorpgpmcelroy approved these changes
Comments have been discussed/addressed and functionality looks good

2021-08-17 08:19 UTC, merged