feature/EUI-3911
hmcts/rpx-xui-webapp pull request #1265
Opened 2021-08-24 08:21 UTC by rayliangatos

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-08-31 15:54 UTC, udaydenduluri33 approved these changes
@rayliangatos Reallocate and Remove Allocate Journey

2021-08-31 16:11 UTC, connorpgpmcelroy requested changes
Just the one src on import that needs to be changed. Happy to approve after that's been changed

2021-08-31 16:11 UTC, connorpgpmcelroy commented on src/role-access/components/case-roles-table/case-roles-table.component.ts
> +import { UserType } from 'src/cases/models/user-type';
src

2021-09-01 12:34 UTC, connorpgpmcelroy approved these changes
Discussed concern with Ray regarding previous ticket which was addressed. Previous comment also addressed

2021-09-01 17:13 UTC, merged