Feature/release2 wa2 b
hmcts/rpx-xui-webapp pull request #1298
Opened 2021-09-08 12:16 UTC by rayliangatos

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-02-15 17:37 UTC, connorpgpmcelroy submitted a review, later dismissed
Approving with very minor comments

2022-02-25 09:31 UTC, udaydenduluri33 submitted a review, later dismissed
This is the release candidate for the WA release 2 and 2.1

2022-02-25 10:07 UTC, connorpgpmcelroy requested changes
Should remove mockLocations file - as far as I can tell not being used and it is significantly big

2022-02-25 10:12 UTC, udaydenduluri33 commented on api/locations/data/location.mock.data.ts
> +
Yes please. Can you do that?

2022-02-25 10:15 UTC, connorpgpmcelroy approved these changes

2022-02-25 10:36 UTC, udaydenduluri33 submitted a review, later dismissed

2022-02-28 09:41 UTC, connorpgpmcelroy approved these changes

2022-02-28 09:51 UTC, sreekanthpuligadda approved these changes
LGTM

2022-02-28 10:01 UTC, udaydenduluri33 approved these changes

2022-02-28 10:04 UTC, merged