persist local storage filters for judicial users
hmcts/rpx-xui-webapp pull request #1343
Opened 2021-09-29 15:05 UTC by kuda1992

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4293?filter=-1

### Change description ###
Changed TaskListComponent  to check the current user and if the user is judicial set the filters to persist locally. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2021-09-30 08:28 UTC, connorpgpmcelroy commented on src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
> +import { AppUtils } from '../../../app/app-utils';
Very minor comment - Could this import be put with others below rather than with the ones above?

2021-09-30 08:31 UTC, connorpgpmcelroy approved these changes
Changes understandable based on session functionality between users - LGTM

2021-09-30 08:32 UTC, connorpgpmcelroy requested changes
Lint error on branch currently

2021-09-30 08:34 UTC, udaydenduluri33 commented on src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
> +    this.appStoreSub = this.store.pipe(select(fromRoot.getUserDetails)).subscribe(
The logic to use which persistence should not be part of this component. 

- We want it as an input parameter.
- The logic should be moved to an Util method.
- Lastly, the container component should call the util method and pass it to this component as Input

2021-09-30 08:34 UTC, udaydenduluri33 requested changes
@kuda1992 Please see my comments below

2021-10-01 09:57 UTC, udaydenduluri33 approved these changes
@kuda1992 thanks for making the changes

2021-10-14 11:17 UTC, merged