EUI-4679 Global search date of death validation unhappy path
hmcts/rpx-xui-webapp pull request #1418
Opened 2021-10-29 14:48 UTC by johnbenjamin-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4679

### Change description ###
Global Search - Date of death validation unhappy path

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-11-01 16:20 UTC, Mo-Lala84 approved these changes
approved

2021-11-01 17:29 UTC, adnanakgun approved these changes

2021-11-02 05:30 UTC, Daniel-Lam requested changes
@johnbenjamin-hmcts - just one, very minor change that is needed.

2021-11-02 05:30 UTC, Daniel-Lam commented on src/search/containers/search-form/search-form.component.spec.ts
> +import { SearchFormControl } from 'src/search/enums';
@johnbenjamin-hmcts - please change this to a relative import.

2021-11-02 09:58 UTC, johnbenjamin-hmcts commented
> @johnbenjamin-hmcts - just one, very minor change that is needed.

Thank you @Daniel-Lam, I have now applied the fix.

2021-11-02 10:15 UTC, Daniel-Lam approved these changes

2021-11-04 08:37 UTC, merged