Feature/e UI 3750 display role type for assign and reassign
hmcts/rpx-xui-webapp pull request #1476
Opened 2021-11-16 09:28 UTC by kuda1992

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-11-16 17:32 UTC, connorpgpmcelroy requested changes
Few comments to make

2021-11-16 17:32 UTC, connorpgpmcelroy commented on src/work-allocation-2/work-allocation2.module.ts
> +  declarations: [...fromContainers.containers, TaskAssignmentChooseRoleComponent],
Why is TaskAssignmentChooseRoleComponent mentioned here?

2021-11-16 17:38 UTC, kuda1992 commented on src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts
> +                    taskAndCaseworkers: { data: mockTasks[0] },
merge gone wrong

2021-11-17 12:23 UTC, connorpgpmcelroy approved these changes
Comments addressed - LGTM

2021-11-17 16:38 UTC, udaydenduluri33 approved these changes

2021-11-25 14:51 UTC, merged