E UI 4708 hearing venue service location
hmcts/rpx-xui-webapp pull request #1483
Opened 2021-11-18 09:39 UTC by waynepHMCTS

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-4708

### Change description ###
Consumption off Service location  with tag 1.4.9-search-location-component-common

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2021-11-18 11:04 UTC, kuda1992 approved these changes
Looks goof

2021-11-18 17:12 UTC, rayliangatos requested changes

2021-11-18 17:12 UTC, rayliangatos commented on src/cases/containers/case-hearings/case-hearings.component.html
> +     [routerLink]="['/', 'hearings', 'request', 'locationSearch']"
Can we revert this and ask QA to test on:
/hearings/request/locationSearch url directly?

2021-11-18 17:12 UTC, rayliangatos commented on src/hearings/containers/request-hearing/location-search-container/location-search-container.component.spec.ts
> +fdescribe('LocationSearchContainerComponent', () => {
fdescribe

2021-11-18 17:12 UTC, rayliangatos commented on src/hearings/containers/request-hearing/location-search-container/location-search-container.component.ts
> +      this.serviceId = id
missed ;

2021-11-18 17:12 UTC, rayliangatos commented on src/hearings/containers/request-hearing/request-hearing.component.html
> +        </div>
@Kartheek-S has a pr https://github.com/hmcts/rpx-xui-webapp/pull/1481 which should be merged first, so your pr should depends on his, and this changes is not necessary anymore if we use parent route. As this seems duplicated with location-search-container.component.html

2021-11-18 17:12 UTC, rayliangatos commented on src/hearings/hearings.module.ts
> +    MatInputModule
You probably don't need this Mat** in the hearings module, as we assume all the dependencies should be in common-lib module.

2021-11-18 17:45 UTC, waynepHMCTS commented on package.json
> +    "build:ng": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod build",
memory problem

2021-11-19 00:45 UTC, waynepHMCTS commented on src/cases/case-feature.module.spec.ts
>  });
This have been merged in by the feature branch

2021-11-19 09:16 UTC, waynepHMCTS commented on package.json
> +    "build:prod": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod",
Memory problem

2021-11-19 15:06 UTC, rayliangatos commented on src/hearings/hearings.routes.ts
> +      },
merge issue, duplicated welsh-hearing?

2021-11-19 15:20 UTC, rayliangatos commented on src/hearings/hearings.routes.ts
> +    component: null,
it needs to be reverted to:
component: RequestHearingComponent,

2021-11-19 15:21 UTC, rayliangatos commented on src/hearings/containers/request-hearing/location-search-container/location-search-container.component.html
> +<exui-app-header></exui-app-header>
The exui-app-header line needs to be removed, as it has been defined in parent component.

2021-11-19 15:42 UTC, rayliangatos approved these changes

2021-11-19 15:46 UTC, Kartheek-S approved these changes

2021-11-23 09:08 UTC, rayliangatos approved these changes

2021-11-23 09:12 UTC, Kartheek-S approved these changes

2021-11-23 14:20 UTC, merged