E UI 4637 hearings requirements case flags language and reasonable adjustments
hmcts/rpx-xui-webapp pull request #1563
Opened 2021-12-10 15:29 UTC by waynepHMCTS

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-12-13 15:40 UTC, rayliangatos commented on api/hearings/models/case-flag-group.model.ts
> +}
I mean move to angular src folder not api folder, not 'remove', as this is not used in the api. only the angular component needs to group this flags.

2021-12-14 16:20 UTC, adnanakgun commented on src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
> +fdescribe('HearingRequirementsComponent', () => {
Maybe remove this `f`.

2021-12-14 16:59 UTC, rayliangatos commented on src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
> +  beforeEach(() => {
two beforeEach

2021-12-14 16:59 UTC, rayliangatos commented on src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts
> +    spyOn(component, 'assignHearingValue').and.callThrough();
This will cause the fake unit tests coverage rate.
These two spys actually asked the tests to skip the two main method.

2021-12-14 17:03 UTC, rayliangatos requested changes
Refactored your pr in:
https://github.com/hmcts/rpx-xui-webapp/pull/1571
and all test issues are resovled.

2022-02-24 18:43 UTC, closed without merging