E UI 4654 request hearing party attendance page display and function UI to change to participant
hmcts/rpx-xui-webapp pull request #1589
Opened 2021-12-22 11:27 UTC by waynepHMCTS

Please remove this line and everything above and fill the following sections:
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4686

### Change description ###

hearing attendance allow editing off party channel and estimation

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-12-22 16:45 UTC, johnbenjamin-hmcts requested changes
@waynepHMCTS, minor changes required.

2021-12-22 16:45 UTC, johnbenjamin-hmcts commented on src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
> +        map(hearingList => hearingList.hearingListMainModel ? hearingList.hearingListMainModel.hmctsServiceID : '')
This method has too many tab indentation, 4 spaces instead of 2.

2021-12-22 16:45 UTC, johnbenjamin-hmcts commented on src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.scss
> +    font-size: 1.1875rem;
Looks like too many tab indentation in this file as well.

2021-12-23 09:20 UTC, johnbenjamin-hmcts approved these changes
Approved

2021-12-23 09:32 UTC, Kartheek-S approved these changes

2021-12-23 09:32 UTC, Kartheek-S commented on src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
> +import { RefDataModel } from 'src/hearings/models/refData.model';
relative path

2021-12-23 09:32 UTC, Kartheek-S commented on src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts
> +import { ValidatorsUtils } from 'src/hearings/utils/validators.utils';
relative path

2021-12-23 09:32 UTC, Kartheek-S commented on src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
> +import { ValidatorsUtils } from 'src/hearings/utils/validators.utils';
relative path

2023-08-23 12:47 UTC, closed without merging