Feature/e UI 5013 panel hearing answer
hmcts/rpx-xui-webapp pull request #1788
Opened 2022-02-23 19:01 UTC by SivaprakasamSivaprakasam

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-5013

### Change description ###
Display panel requirement details on the summary page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-02-24 13:40 UTC, rayliangatos requested changes

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/converters/hearing-panel-include-members.converter.ts
> +}
This seems to be siimilar to the exclude one, it should extract to common method to avoid duplication.

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/converters/hearing-panel-other-panel-roles.converter.ts
> +          return;
should return the right type.

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/converters/hearing-panel-other-panel-roles.converter.ts
> +                    return;
it probably best to recursively search the value from the key in this data object, rather than find to the depth of only secode level.

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/converters/hearing-panel-required.converter.ts
> +        return state.hearingRequest.hearingRequestMainModel.hearingDetails.panelRequirements.panelPreferences.length > 0
How about if there are some judges users inside this panelRequirements.panelPreferences, and then this is showing yes, but the memberType here is for PANEL_MEMBER only, so it needs to filter that.

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/resolvers/panel-details.resolver.ts
> +export class PanelDetailsResolver implements Resolve<JudicialUserModel[]> {
it shouldn't be called PanelDetailsResolver here, if it's also used by the judgeDetailsResolver.

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/resolvers/panel-details.resolver.ts
> +  public getPanelMemberId$(): string[] {
why a $ inside a method?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/resolvers/panel-details.resolver.ts
> +  public getReferenceData$(serviceId): Observable<JudicialUserModel[]> {
why a $ inside a method?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/resolvers/panel-details.resolver.ts
> +export class PanelDetailsResolver implements Resolve<JudicialUserModel[]> {
Also I think @Kartheek-S has created this resolver.

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/templates/hearing-create-edit-summary.template.ts
> +      '<h1 class="govuk-heading-l">Check your answers before sending your request</h1>',
necessary change to break into two lines?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/templates/hearing-create-edit-summary.template.ts
> +        changeLink:
necessary change to break into two lines?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/templates/hearing-create-edit-summary.template.ts
> +        changeLink:
necessary change to break into two lines?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/templates/hearing-create-edit-summary.template.ts
> +      },
how do you achieve the show/hide for YES/NO?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/templates/hearing-create-edit-summary.template.ts
> +    sectionHTMLTitle:
necessary change to break into two lines?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/templates/hearing-create-edit-summary.template.ts
> +      '<h2 class="govuk-heading-m">Additional instructions</h2>',
necessary change to break into two lines?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/templates/hearing-create-edit-summary.template.ts
> +          '/hearings/request/hearing-additional-instructions#additionalInstructionsTextarea',
necessary change to break into two lines?

2022-02-24 13:40 UTC, rayliangatos commented on src/hearings/models/hearings.enum.ts
> +  HEARING_PANEL_REQUIRED,
if this HEARING_PANEL_REQUIRED is created could the HEARING_PANEL being deleleted?

2022-02-24 13:40 UTC, rayliangatos commented on api/hearings/data/serviceHearingValues.mock.data.ts
> +import { ServiceHearingValuesModel } from '../models/serviceHearingValues.model'
; is removed?

2022-02-24 16:32 UTC, kuda1992 requested changes
Few changes

2022-02-24 16:32 UTC, kuda1992 commented on api/hearings/models/panelRequirements.model.ts
> +  roleType?: string[];
Why is everything optional?

2022-02-24 16:32 UTC, kuda1992 commented on src/hearings/converters/hearing-panel-required.converter.ts
> +          return;
Very strange pattern why are we returning `void`. Can we just not use filter?

2022-02-24 16:32 UTC, kuda1992 commented on src/hearings/resolvers/other-panel-roles.resolver.ts
> +          return data.map((member) => member);
What is the point of `map` here?

2022-02-24 16:32 UTC, kuda1992 commented on src/hearings/resolvers/panel-judge-details.resolver.ts
> +  public getPanelMemberId(): string[] {
Rename this method to `getPanelMemberIds()`

2022-02-24 16:32 UTC, kuda1992 commented on src/hearings/resolvers/panel-judge-details.resolver.ts
> +        map((data) => {
The map is not needed at all.

2022-04-26 14:02 UTC, closed without merging

2022-04-26 14:03 UTC, SivaprakasamSivaprakasam commented
not required