hearing tab failure handling
hmcts/rpx-xui-webapp pull request #1879
Opened 2022-03-16 19:40 UTC by SivaprakasamSivaprakasam

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-5444

### Change description ###

Hearing tab error/failure handling

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-17 10:49 UTC, rayliangatos requested changes
Logical error, this API is from the getHearingList not get Hearing request.
And we also need to change the mock data to simulate the unhappy path scenario.

2022-03-17 10:49 UTC, rayliangatos commented on src/cases/containers/case-hearings/case-hearings.component.ts
> +      if (state && state.hearingRequest && state.hearingRequest.lastError) {
this is the wrong place, it should be the hearingList

2022-03-17 10:49 UTC, rayliangatos commented on src/hearings/store/actions/hearing-request.action.ts
> +}
this is wrong place, it should be in the hearingLIst

2022-03-17 10:49 UTC, rayliangatos commented on src/hearings/store/reducers/hearing-request.reducer.ts
> +    case fromActions.LOAD_HEARING_REQUEST_FAILURE: {
this should be the hearingList

2022-03-17 21:12 UTC, rayliangatos commented on api/hearings/hearing.mock.ts
>          EMPTY_HEARINGS_LIST,
```suggestion
      if (caseIds[0].endsWith('6') {
        return [
          500,
          null,
        ];
      }
      return [
        200,
        ...EMPTY_HEARINGS_LIST,
```

2022-03-18 15:43 UTC, rayliangatos commented on src/cases/containers/case-hearings/case-hearings.component.html
> +          <a href="javascript:void(0)" [routerLink]="['/', 'cases', 'case-details', caseId, 'hearings']"
it seems angular will do nothing to navigate to the same page. so we need to use (click)="reload()"

on the reload() dispatch an action
this.hearingStore.dispatch(new fromHearingStore.LoadAllHearings(this.caseId));

2022-03-18 17:00 UTC, rayliangatos approved these changes
looks good to me, thanks for addressing the comments.

2022-03-18 18:50 UTC, Kartheek-S approved these changes

2022-03-22 09:31 UTC, merged