Add ccd toolkit tag
hmcts/rpx-xui-webapp pull request #1911
Opened 2022-03-28 10:56 UTC by connorpgpmcelroy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-5569
https://tools.hmcts.net/jira/browse/EUI-5591
https://tools.hmcts.net/jira/browse/EUI-5615
https://tools.hmcts.net/jira/browse/EUI-5632
https://tools.hmcts.net/jira/browse/EUI-5659
https://tools.hmcts.net/jira/browse/EUI-5749

### Change description ###
Adding toolkit changes to enable functionality when task not required for event

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-03-29 15:43 UTC, udaydenduluri33 approved these changes
@connorpgpmcelroy  thanks for the changes

2022-03-30 09:44 UTC, udaydenduluri33 submitted a review, later dismissed

2022-03-31 13:36 UTC, turner1979 commented on src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts
> +      }
block could be refined slightly e.g:

```
const { caseId } = this.route.snapshot.queryParams;
if (caseId) {
  this.caseId = caseId.replace(/-/g, '');
}

```

2022-03-31 13:39 UTC, turner1979 requested changes
@connorpgpmcelroy 1 minor suggestion from me otherwise looks good

2022-04-01 13:07 UTC, udaydenduluri33 approved these changes

2022-04-01 13:50 UTC, udaydenduluri33 approved these changes

2022-05-03 08:40 UTC, udaydenduluri33 approved these changes

2022-05-04 08:21 UTC, udaydenduluri33 approved these changes

2022-05-05 09:11 UTC, tarikdogan-hmcts approved these changes

2022-05-05 09:37 UTC, udaydenduluri33 approved these changes

2022-05-05 09:39 UTC, merged