EUI-5539 WA-filter logic implimented for SSCS
hmcts/rpx-xui-webapp pull request #2043
Opened 2022-05-27 16:05 UTC by tarikdogan-hmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-5539

### Change description ###

Change to what services can be selected in the Show work filter in My work

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-05-30 14:37 UTC, connorpgpmcelroy requested changes
Minor changes requested

2022-05-30 14:37 UTC, connorpgpmcelroy commented on src/work-allocation-2/components/task-list-filter/task-list-filter.component.spec.ts
> +import * as fromAppStore from '../../../app/store';
Import should be at top of other '../' imports

2022-05-30 15:38 UTC, udaydenduluri33 commented on src/app/app.constants.ts
> +export const SERVICE_OPTIONS_LIST = [{key: 'IA', label: 'Immigration and Asylum'}, {key: 'SSCS', label: 'Social security and child support'}];
Unuderstand this is only added for testing purposes

2022-05-31 08:23 UTC, udaydenduluri33 submitted a review, later dismissed

2022-06-01 09:08 UTC, connorpgpmcelroy submitted a review, later dismissed
Comments have been worked on so all good

2022-06-01 09:13 UTC, udaydenduluri33 submitted a review, later dismissed
@tarikdogan-hmcts  Thanks for making the changes

2023-08-23 12:49 UTC, closed without merging