EUI-5498
hmcts/rpx-xui-webapp pull request #2234
Opened 2022-08-09 16:53 UTC by maliumer

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-5498

### Change description ###
Welsh language toggle

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-08-10 08:38 UTC, rayliangatos commented on src/app/components/phase-banner/phase-banner.component.html
> +    <a href="#" href="javascript:void(0)" (click)="toggleLanguage('cy')" *ngIf="currentLang == 'en'" class="language">Gymraeg</a>
duplicated href, the one href="#" can be deleted?

2022-08-10 08:38 UTC, rayliangatos commented on src/app/components/phase-banner/phase-banner.component.html
> +    <a href="#" href="javascript:void(0)" (click)="toggleLanguage('en')" *ngIf="currentLang == 'cy'" class="language">English</a>
duplicated href, the one href="#" can be deleted?

2022-08-12 13:11 UTC, rayliangatos commented on src/app/shared/shared.module.ts
> +import { InfoMessageCommService } from './services/info-message-comms.service';
is this redudant?

2022-08-12 13:11 UTC, rayliangatos commented on src/app/components/phase-banner/phase-banner.component.ts
> +  public toggleLanguage(lang: RpxLanguage) {
could this return with void?

2022-08-12 13:22 UTC, MateiHMCTS requested changes

2022-08-12 13:22 UTC, MateiHMCTS commented on src/app/components/phase-banner/phase-banner.component.html
> +                {{'feedback' | rpxTranslate }}<span class="visuallyhidden">(Opens in a new window)</span>
I think "(Opens in a new window)" needs to be translated as well

2022-08-12 15:53 UTC, rayliangatos approved these changes

2022-08-15 08:51 UTC, MateiHMCTS approved these changes

2022-08-15 08:51 UTC, merged