Merge release3 into release4
hmcts/rpx-xui-webapp pull request #2322
Opened 2022-09-14 12:39 UTC by DavidJayakumar

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-6587

### Change description ###

Move the recent canges from release 3 to release 4

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-09-14 14:30 UTC, connorpgpmcelroy requested changes
Have one reuqested change to remove duplicated code

2022-09-14 14:30 UTC, connorpgpmcelroy commented on src/app/components/routing/application-routing.component.ts
> +      }
Is this not just duplicated code?

2022-09-14 15:07 UTC, MateiHMCTS approved these changes
Everything is great!
Just noticed a few styling issues. would appreciate if you can solve them whenever.

2022-09-14 15:07 UTC, MateiHMCTS commented on test/e2e/features/step_definitions/workAccessBookingUI/workAccessPage.steps.js
> +
extra row

2022-09-14 15:07 UTC, MateiHMCTS commented on test/e2e/features/step_definitions/workallocation/common.steps.js
> +
extra row

2022-09-14 15:07 UTC, MateiHMCTS commented on test/e2e/utils/request.js
> +            const config = await this.getRequestConfig(headers);
not aligned

2022-09-14 15:07 UTC, MateiHMCTS commented on test/nodeMock/workAllocation/bookingsData.js
> +            { appointmentId : "100"},
styling issue

2022-09-14 15:07 UTC, MateiHMCTS commented on test/ngIntegration/tests/stepDefinitions/workallocation/waCommon.steps.js
> +                }else{
styling issue

2022-09-14 15:07 UTC, MateiHMCTS commented on test/ngIntegration/tests/stepDefinitions/workallocation/wa2.steps.js
> +
unnecessary row

2022-09-15 08:47 UTC, DavidJayakumar commented on test/e2e/features/pageObjects/caseEditPage.js
> +                // date1.setDate(date1.getDate());
It is functional test. So I will leave it for Sreekanth

2022-09-15 08:48 UTC, DavidJayakumar commented on test/e2e/features/pageObjects/createCaseStartPage.js
>     await e.click();
fixed

2022-09-20 09:35 UTC, merged