Feature/e UI 6516 task permission wa4
hmcts/rpx-xui-webapp pull request #2325
Opened 2022-09-15 10:34 UTC by connorpgpmcelroy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-6516

### Change description ###
Fine grained task permissions for release 4 (turned on by LaunchDarkly feature to keep existing functionality)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-09-15 13:25 UTC, MateiHMCTS requested changes

2022-09-15 13:25 UTC, MateiHMCTS commented on api/workAllocation/utils.spec.ts
> +
styling issue

2022-09-15 13:25 UTC, MateiHMCTS commented on api/configuration/references.ts
> +
styling issue

2022-09-15 13:25 UTC, MateiHMCTS commented on src/work-allocation/services/work-allocation-task.service.ts
>      return this.http.post<any>(`${BASE_URL}`, task);
why any?

2022-09-15 13:25 UTC, MateiHMCTS commented on src/work-allocation/services/work-allocation-task.service.ts
> +  public searchTask(body: { searchRequest: SearchTaskRequest, view: string, refined: boolean }): Observable<TaskResponse> {
why pass refined if not used?

2022-09-15 13:30 UTC, Surekha-HMCTS approved these changes

2022-11-04 13:49 UTC, DavidJayakumar approved these changes
Looks good

2022-11-07 14:40 UTC, Kartheek-S approved these changes

2022-11-18 14:34 UTC, merged