EUI-3967 loading spinner
hmcts/rpx-xui-webapp pull request #2366
Opened 2022-10-04 06:15 UTC by SivaprakasamSivaprakasam

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-3967

### Change description ###

EUI-3967 loading spinner

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-10-04 13:00 UTC, RiteshHMCTS approved these changes

2022-10-04 13:42 UTC, maliumer submitted a review, later dismissed

2023-02-21 16:38 UTC, ronaldmansveld requested changes
For consistency, don't use plain booleans, but use the loading service as exported by the common lib. This way the spinner will show whenever anything that registers itself is loading.

2023-02-24 11:13 UTC, GaryScottHMCTS approved these changes

2023-04-06 15:49 UTC, merged