story/EUI-7113 roles-and-access
hmcts/rpx-xui-webapp pull request #2488
Opened 2022-11-15 20:37 UTC by Kartheek-S

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-7113

### Change description ###
Work allocation R3.5 - Feature toggle R3.5

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-11-21 15:23 UTC, connorpgpmcelroy requested changes
Changes required but looks in the main good to me, thanks for replicating the task permission changes

2022-11-21 15:23 UTC, connorpgpmcelroy commented on api/workAllocation/index.ts
> +      }
Need to remove mockTaskPermissions call now btw please

2022-11-21 15:23 UTC, connorpgpmcelroy commented on src/app/app.constants.ts
> +  updatedTaskPermission: 'updated-task-permission',
two updatedTaskPermission feature calls here - need to be merged

2022-11-21 15:23 UTC, connorpgpmcelroy commented on src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
> +import { AppConstants } from 'src/app/app.constants';
src needs to be replaces

2022-12-13 09:36 UTC, Kartheek-S commented
Changes merged into [EUI-7032](https://github.com/hmcts/rpx-xui-webapp/pull/2516)

2022-12-13 09:36 UTC, closed without merging