Feature/update from r3.5 to 4
hmcts/rpx-xui-webapp pull request #2573
Opened 2022-12-09 15:45 UTC by Surekha-HMCTS

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-12-09 16:33 UTC, connorpgpmcelroy requested changes
Two minor changes to request

2022-12-09 16:33 UTC, connorpgpmcelroy commented on src/app/components/routing/application-routing.component.ts
> +import { combineLatest, Observable, iif, Subscription } from 'rxjs';
iif?

2022-12-09 16:33 UTC, connorpgpmcelroy commented on src/cases/containers/case-viewer-container/case-viewer-container.component.ts
> +import { WAFeatureConfig } from 'src/work-allocation/models/common/service-config.model';
src

2022-12-09 17:07 UTC, connorpgpmcelroy approved these changes
Seems all good to me

2022-12-12 09:14 UTC, DavidJayakumar approved these changes

2022-12-12 09:16 UTC, merged