EUI-7430
hmcts/rpx-xui-webapp pull request #2595
Opened 2022-12-16 09:52 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-7430

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-05 11:57 UTC, connorpgpmcelroy approved these changes
LGTM

2023-01-05 11:59 UTC, DavidJayakumar submitted a review, later dismissed

2023-01-06 11:12 UTC, connorpgpmcelroy requested changes
baseLocation should not be being changed to primaryLocation as is shown within these changes  - needs to be kept as baseLocation

2023-01-06 11:49 UTC, connorpgpmcelroy submitted a review, later dismissed
LGTM

2023-01-06 11:53 UTC, udaydenduluri33 approved these changes
LGTM

2023-01-16 10:17 UTC, Mo-Lala84 approved these changes
approved

2023-01-16 10:17 UTC, udaydenduluri33 approved these changes

2023-01-16 10:28 UTC, phillip-whitaker-hmcts commented on api/user/utils.ts
>  }
it seems in this method nothing has been changed apart from removing a comment, I would try and refrain from doing this to simplify the code reviews.

2023-01-16 10:28 UTC, phillip-whitaker-hmcts commented on api/workAllocation/util.ts
> +  );
The predicate in this filter method is complex. Try and break it down. There really should be a maximum of 2-3 equality checks within a single statement for readability.

2023-01-16 10:32 UTC, merged