EUI-6186 Focus at the top of page fix on route change
hmcts/rpx-xui-webapp pull request #2765
Opened 2023-02-08 16:45 UTC by GaryScottHMCTS

### JIRA link (if applicable) ###
[EUI-6186](https://tools.hmcts.net/jira/browse/EUI-6186)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-08 17:15 UTC, RiteshHMCTS requested changes
instead of adding style in component, can you create separate scss file and refer in component. we never follow this approach

2023-02-09 09:42 UTC, RiteshHMCTS approved these changes, later dismissed

2023-02-09 09:55 UTC, Kartheek-S approved these changes

2023-02-09 09:55 UTC, johnbenjamin-hmcts approved these changes

2026-08-01 19:24 UTC, closed without merging