EUI-4129: Activity Tracker
hmcts/rpx-xui-webapp pull request #2860
Opened 2023-03-14 10:25 UTC by LucaDelBuonoHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4129

### Change description ###
WebSocket Activity Tracker

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

2023-03-22 11:47 UTC, deanbullock-hmcts approved these changes, later dismissed
Approved. Lots of formatting changes make the diff quite noisy. Something to look at getting everyone's code editor formatters in-line

2023-03-22 12:22 UTC, Mo-Lala84 submitted a review, later dismissed
approved

2023-03-22 14:26 UTC, bradley-hmcts submitted a review, later dismissed

2025-11-03 11:48 UTC, connorpgpmcelroy requested changes
Needs a few changes

2025-11-03 11:48 UTC, connorpgpmcelroy commented on api/application.ts
> +    app.use(helmet.contentSecurityPolicy({
This is no longer needed and should not be necessary - you should re-evaluate this file because I don't think any of the above is necessary unless it is relevant for activity tracker (which I don't think it is)

2025-11-03 11:48 UTC, connorpgpmcelroy commented on src/cases/resolvers/activity.resolver.ts
> +    return of(this.activityService.mode !== ActivityService.MODES.off);
This boolean is referred to twice - should be a boolean variable

2025-11-03 11:48 UTC, connorpgpmcelroy commented on src/work-allocation/components/case-name-field/case-name-field.component.ts
> +      if (this.caseId && this.jurisdiction && this.caseType) {
Don't think these are changes relevant to the ticket but there's a double if check for caseId here, should be easy enough to remove/edit

2025-11-03 11:48 UTC, connorpgpmcelroy commented on src/work-allocation/components/case-reference-field/case-reference-field.component.ts
> +      if (this.caseReference && this.jurisdiction && this.caseType) {
Same as above

2025-11-03 11:48 UTC, connorpgpmcelroy commented on package.json
>      "@hmcts/rpx-xui-node-lib": "2.30.7-csp-final-change-3",
Note: Just pointing out that the node-lib changes to csp are present so the application.ts changes are definitely unneccessary

2025-11-03 18:03 UTC, balajisridharanhmcts commented on src/work-allocation/components/case-reference-field/case-reference-field.component.ts
> +      if (this.caseReference && this.jurisdiction && this.caseType) {
Done

2025-11-03 18:04 UTC, balajisridharanhmcts commented on src/work-allocation/components/case-name-field/case-name-field.component.ts
> +      if (this.caseId && this.jurisdiction && this.caseType) {
Done

2025-11-03 18:04 UTC, balajisridharanhmcts commented on src/cases/resolvers/activity.resolver.ts
> +    return of(this.activityService.mode !== ActivityService.MODES.off);
Done

2025-11-03 18:04 UTC, balajisridharanhmcts commented on api/application.ts
> +    app.use(helmet.contentSecurityPolicy({
Done

2025-11-04 10:33 UTC, gregs-cgi commented
Updated the base target to CME-782 (Angular 20 branch) for ease of review

2025-11-05 11:36 UTC, connorpgpmcelroy approved these changes, later dismissed
Approving because my concerns are now minor and I won't be here for the second half of the day to change my review, however would ideally like those comments addressed

2025-11-05 11:36 UTC, connorpgpmcelroy commented on src/cases/resolvers/activity.resolver.ts
> +    return of(this.activityService.mode !== ActivityService.MODES.off);
Hasn't actually been replaced here though right? Should be return of(this.isActivityEnabled())?

2025-11-05 11:36 UTC, connorpgpmcelroy commented on src/work-allocation/components/case-name-field/case-name-field.component.ts
> +        caseId = encodeURIComponent(this.caseId);
Again we have if (caseId) { if (caseId && ...), same below with caseReference. We don't need the if (caseId) { first check because we'll be checking it again in the next if statement

2025-11-05 11:36 UTC, connorpgpmcelroy commented on src/work-allocation/components/case-reference-field/case-reference-field.component.ts
> +      if (caseReference && jurisdiction && caseType) {
Same as above, don't need two ifs here

2025-11-05 12:50 UTC, balajisridharanhmcts commented on src/work-allocation/components/case-reference-field/case-reference-field.component.ts
> +      if (caseReference && jurisdiction && caseType) {
Done, as above fix

2025-11-05 12:50 UTC, balajisridharanhmcts commented on src/work-allocation/components/case-name-field/case-name-field.component.ts
> +        caseId = encodeURIComponent(this.caseId);
Missed in previous commits, Removed nested if and updated line 26 in activity.resolver.ts to check isActivityEnabled flag

2026-08-01 19:24 UTC, closed without merging