EXUI-282 removing booking url to avoid unncessary redirect
hmcts/rpx-xui-webapp pull request #3032
Opened 2023-05-24 08:51 UTC by RiteshHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-282

### Change description ###
removing booking url from guard to avoid unncessary redirect

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-05-24 12:48 UTC, bradley-hmcts approved these changes

2023-05-24 14:06 UTC, andywilkinshmcts submitted a review, later dismissed

2023-06-05 08:53 UTC, deanbullock-hmcts approved these changes

2023-06-07 14:44 UTC, deanbullock-hmcts approved these changes

2023-06-07 15:07 UTC, deanbullock-hmcts requested changes
Can we add some test coverage @RiteshHMCTS to cover the logic in auth-guard please?

As part of the new ways of working under SE and aligning with more CI/CD and less SRT we are going to need more confidence the changes we make are under test.

2023-06-08 09:23 UTC, deanbullock-hmcts approved these changes

2023-06-08 09:52 UTC, andywilkinshmcts approved these changes
Bit naughty that this also includes a text change

2023-06-08 10:19 UTC, merged