Feature/e UI 8412
hmcts/rpx-xui-webapp pull request #3048
Opened 2023-05-31 12:03 UTC by MateiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8412

### Change description ###
raise a query display

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-05-31 12:10 UTC, Daniel-Lam requested changes
@MateiHMCTS - very minor comment; the rest is OK

2023-05-31 12:10 UTC, Daniel-Lam commented on src/cases/containers/query-management-container/query-management-container.component.ts
> +  public ngOnInit() {
@MateiHMCTS - return type missing

2023-05-31 12:10 UTC, Kartheek-S approved these changes

2023-05-31 12:12 UTC, Daniel-Lam approved these changes

2023-06-14 09:28 UTC, MateiHMCTS commented
PRs merged together with [EUI-8379](https://tools.hmcts.net/jira/browse/EUI-8379)

2023-06-14 09:28 UTC, closed without merging