Tech/pact wa feature team judicial
hmcts/rpx-xui-webapp pull request #3088
Opened 2023-06-15 10:58 UTC by connorpgpmcelroy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8135

### Change description ###
Pact tests for rdJudicial

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-06-15 13:24 UTC, DavidJayakumar requested changes
@connorpgpmcelroy Please remove comments

2023-06-15 13:24 UTC, DavidJayakumar commented on api/test/pact/pact-tests/rdJudicial/prdGetJudicialUsers.spec.ts
> +  // RESPONSE_BODY.push(user2);
comment has to be removed

2023-06-15 13:24 UTC, DavidJayakumar commented on api/test/pact/pact-tests/rdJudicial/getJudicialUsersSearch.spec.ts
> +  // RESPONSE_BODY.push(user2);
comment has to be removed

2023-06-15 13:37 UTC, DavidJayakumar approved these changes, later dismissed
Looks good

2023-06-23 15:29 UTC, udaydenduluri33 submitted a review, later dismissed

2023-06-26 10:14 UTC, DavidJayakumar submitted a review, later dismissed
LGTM

2023-06-28 10:21 UTC, DavidJayakumar approved these changes
LGTM

2026-08-01 19:23 UTC, closed without merging