Fix pagination issue
hmcts/rpx-xui-webapp pull request #3145
Opened 2023-07-07 15:28 UTC by connorpgpmcelroy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-8632

### Change description ###
Fix pagination issue
Also ensure filter resets lists correctly for each task list

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-07-10 08:48 UTC, DavidJayakumar requested changes
@connorpgpmcelroy Please see my comments

2023-07-10 08:48 UTC, DavidJayakumar commented on src/work-allocation/containers/all-work-task/all-work-task.component.ts
> +  private initialFilterRan = false;
Name can be isInitialFilterRange and type is missing

2023-07-10 08:48 UTC, DavidJayakumar commented on src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
> +  private goneBackCount = 0;
Specify type

2023-07-10 11:17 UTC, udaydenduluri33 submitted a review, later dismissed
LGTM

2023-07-10 13:02 UTC, DavidJayakumar approved these changes
LGTM

2023-07-10 13:19 UTC, Mo-Lala84 approved these changes
approved

2023-07-11 11:45 UTC, Mo-Lala84 approved these changes
approved

2023-07-11 11:54 UTC, udaydenduluri33 approved these changes

2023-07-11 13:02 UTC, merged