COT-427 IAC Hearings Onboarding: Configure ExUI to point to IAC hearings endpoints
hmcts/rpx-xui-webapp pull request #3169
Opened 2023-07-20 10:19 UTC by mwaheedanjum

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-07-20 10:23 UTC, rajeshthuraiyur approved these changes
LGTM

2023-07-20 10:47 UTC, andywilkinshmcts submitted a review, later dismissed

2023-07-20 10:47 UTC, andywilkinshmcts commented on config/default.json
> +      "hearingsJurisdictions": "SSCS,PRIVATELAW,CIVIL,IAC",
This should be IA, not IAC

2023-07-20 10:47 UTC, andywilkinshmcts commented on config/default.json
> +      "iac": {
This should be "ia" not "iac"

2023-07-25 12:56 UTC, andywilkinshmcts requested changes
Why does the pr include api/.yarn/install-state.gz
This shouldn't be checked in

2023-07-25 13:00 UTC, mwaheedanjum commented
> Why does the pr include api/.yarn/install-state.gz This shouldn't be checked in

deleted

2023-07-25 13:04 UTC, andywilkinshmcts approved these changes

2023-07-25 13:15 UTC, rajeshthuraiyur approved these changes
LGTM

2023-07-27 09:37 UTC, merged