Feature/EUI 8568
hmcts/rpx-xui-webapp pull request #3176
Opened 2023-07-25 14:24 UTC by DavidJayakumar

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-8568

### Change description ###

Restricted Case Access - Pact test 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-25 16:22 UTC, Daniel-Lam requested changes
@DavidJayakumar - just one very minor thing to check

2023-07-25 16:22 UTC, Daniel-Lam commented on api/test/pact/pact-tests/rolesAccess/getAccessRolesByCaseId.spec.ts
> +        console.log(err.stack);
@DavidJayakumar - do other Pact tests `console.log` the error? (Not sure myself as I've not done any of these)

2023-07-25 16:23 UTC, johnbenjamin-hmcts approved these changes

2023-07-26 08:15 UTC, Daniel-Lam approved these changes

2023-07-26 14:35 UTC, merged