Bug/ex UI 349 table visual bug
hmcts/rpx-xui-webapp pull request #3253
Opened 2023-09-04 10:41 UTC by OgunyemiO

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EXUI-349

### Change description ###
Css change to fix table column misalignment.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2023-09-05 09:20 UTC, andywilkinshmcts requested changes
I'm a bit worried about using an absolute pixel measurement - relevant to users with scaled/zoomed displays. 73  px is about 4.5em - maybe use that?

2023-09-06 09:14 UTC, andywilkinshmcts submitted a review, later dismissed

2023-09-06 09:15 UTC, andywilkinshmcts approved these changes, later dismissed

2023-09-06 09:30 UTC, RiteshHMCTS submitted a review, later dismissed

2026-07-31 19:31 UTC, closed without merging