Feature/EUI 8901
hmcts/rpx-xui-webapp pull request #3325
Opened 2023-10-16 08:18 UTC by DavidJayakumar

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/EUI-8901

### Change description ###

Add translation to hearings journey

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2023-10-16 15:14 UTC, johnbenjamin-hmcts requested changes
There are few changes requested, and one additional comment about moving the following block of code into a separate file and reference it in the .spec files

```
@Pipe({ name: 'rpxTranslate' })
class RpxTranslateMockPipe implements PipeTransform {
  public transform(value: string): string {
    return value;
  }
}
```

2023-10-16 15:14 UTC, johnbenjamin-hmcts commented on src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.html
> +          <dd class="govuk-summary-list__value">{{isPaperHearing ? 'Yes' : 'No'}}</dd>
Yes No translation required?

2023-10-16 15:14 UTC, johnbenjamin-hmcts commented on src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.html
> +                      {{actualHearingDay.notRequired ? 'No' : 'Yes'}}
Yes No translation required?

2023-10-16 15:14 UTC, johnbenjamin-hmcts commented on src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.html
> +                      fragment="hearingDate">Change</a>
Translation for Change link.

2023-10-16 15:14 UTC, johnbenjamin-hmcts commented on src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.html
> +                          fragment="hearingDate">Change</a>
Translation for Change link.

2023-10-16 15:14 UTC, johnbenjamin-hmcts commented on src/hearings/containers/hearing-actuals/hearing-actuals-edit-summary/hearing-actuals-edit-summary.component.html
> +                          fragment="hearingDate">Change</a>
Translation for Change link.

2023-10-16 15:14 UTC, johnbenjamin-hmcts commented on src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
> +    const onPeperHearing = this.attendanceFormGroup.controls.paperHearing.value === RadioOptions.YES;
Typo in onP**e**perHearing.

2023-10-17 09:56 UTC, DavidJayakumar commented on src/hearings/components/hearing-amend-warning-msg/hearing-amend-warning-msg.component.html
>      {{ warningMsg }}
Added

2023-10-17 10:41 UTC, johnbenjamin-hmcts approved these changes

2023-10-17 11:25 UTC, udaydenduluri33 approved these changes

2023-10-25 11:37 UTC, merged