Updated custom-environment-variables.json to include ET
hmcts/rpx-xui-webapp pull request #3330
Opened 2023-10-17 12:58 UTC by ss-evoco

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-10-17 17:38 UTC, andywilkinshmcts approved these changes

2023-10-18 11:42 UTC, andywilkinshmcts approved these changes

2023-10-18 13:02 UTC, RiteshHMCTS approved these changes

2023-10-18 13:22 UTC, andywilkinshmcts requested changes
That's not how it's supposed to work

2023-10-18 13:29 UTC, andywilkinshmcts commented on config/custom-environment-variables.json
> +      "hearingsJurisdictions": "SSCS,PRIVATELAW,CIVIL,IA,EMPLOYMENT",
"hearingsJurisdictions": "HEARINGS_JURISDICTIONS",

2023-10-18 13:45 UTC, closed without merging