Hearings Welsh and Yes No
hmcts/rpx-xui-webapp pull request #3347
Opened 2023-10-31 11:00 UTC by johnbenjamin-hmcts

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/EUI-8956

### Change description ###
Remove the Welshify changes from the Hearings PR

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-11-07 10:13 UTC, udaydenduluri33 approved these changes

2023-11-07 10:24 UTC, connorpgpmcelroy approved these changes
Approved with minor comment

2023-11-07 10:24 UTC, connorpgpmcelroy commented on src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.html
> +              <label class="govuk-label govuk-radios__label" for="noSpecificJudge">{{ 'Do you want a specific judge?' | rpxTranslate : null : 'No' }}</label>
Minor comment: 'Do you want a specific judge?' especially as it is repeated should be a string constant/variable

2023-11-10 11:07 UTC, connorpgpmcelroy requested changes
Minor change requested

2023-11-10 11:07 UTC, connorpgpmcelroy commented on src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
> +import { ValidatorsUtils } from 'src/hearings/utils/validators.utils';
src used here

2023-11-10 11:10 UTC, DavidJayakumar commented on src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
> +import { ValidatorsUtils } from 'src/hearings/utils/validators.utils';
done

2023-11-10 11:32 UTC, udaydenduluri33 approved these changes

2023-11-10 11:33 UTC, connorpgpmcelroy approved these changes
LGTM

2023-11-10 15:28 UTC, connorpgpmcelroy submitted a review, later dismissed
LGTM

2023-11-10 16:52 UTC, udaydenduluri33 approved these changes

2024-01-30 12:26 UTC, DavidJayakumar commented
3429 is the latest. so closing this PR

2024-01-30 12:26 UTC, closed without merging