remove duplicate jurisdiction response from API
hmcts/rpx-xui-webapp pull request #3354
Opened 2023-11-03 13:05 UTC by OgunyemiO

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/EXUI-1023

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [x ] Does this PR introduce a breaking change

2023-11-03 13:28 UTC, RiteshHMCTS approved these changes

2023-11-03 16:23 UTC, RiteshHMCTS requested changes
@OgunyemiO la can you add unit test to tackle this issue

2023-11-06 11:13 UTC, OgunyemiO commented
> @OgunyemiO la can you add unit test to tackle this issue

@RiteshHMCTS Unit test added. Thanks

2023-11-06 11:28 UTC, RiteshHMCTS approved these changes

2023-11-07 10:43 UTC, RiteshHMCTS approved these changes

2023-11-07 10:49 UTC, andywilkinshmcts submitted a review, later dismissed

2023-11-07 10:58 UTC, olusegz07 approved these changes

2023-11-07 14:43 UTC, RiteshHMCTS submitted a review, later dismissed

2023-11-08 10:58 UTC, olusegz07 approved these changes

2023-11-08 16:10 UTC, andywilkinshmcts submitted a review, later dismissed

2024-01-16 12:16 UTC, merged