fix: EXUI-1135 resolve issue with amend appearing
hmcts/rpx-xui-webapp pull request #3407
Opened 2023-12-11 12:15 UTC by olusegz07

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-12-11 12:21 UTC, RiteshHMCTS requested changes
@olusegz07 can you add some unit test to cover this scenario?

2023-12-11 12:24 UTC, andywilkinshmcts approved these changes

2023-12-14 10:17 UTC, OgunyemiO approved these changes

2023-12-15 10:17 UTC, OgunyemiO approved these changes

2023-12-20 16:34 UTC, RiteshHMCTS approved these changes

2024-01-16 11:31 UTC, merged