Add validation error
hmcts/rpx-xui-webapp pull request #3465
Opened 2024-01-18 17:33 UTC by DavidJayakumar

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/EUI-9097

### Change description ###

Implement existing Validation check at submission

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2024-01-19 16:31 UTC, johnbenjamin-hmcts requested changes

2024-01-19 16:31 UTC, johnbenjamin-hmcts commented on src/hearings/containers/request-hearing/request-hearing.component.ts
> +  public validationErrors: { id: string, message: string }[] = [];
@DavidJayakumar - do we need this declaration here?

2024-01-19 16:38 UTC, johnbenjamin-hmcts approved these changes

2024-01-22 09:57 UTC, udaydenduluri33 approved these changes

2024-01-23 16:19 UTC, merged