remove unneeded item from CYA page if already removed from workflow.
hmcts/rpx-xui-webapp pull request #3483
Opened 2024-01-23 13:23 UTC by OgunyemiO

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/EXUI-1077

### Change description ###

remove unneeded item from CYA page if already removed from workflow.

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-01-23 13:35 UTC, RiteshHMCTS commented on src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.ts
> +  removeUnnecessarySummaryTemplateItems() {
can you put the function type whether private/public

2024-01-23 13:35 UTC, RiteshHMCTS commented on src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.ts
> +  private getScreenFlowFromStore(hearingStore) {
add unit test to cover this function

2024-01-23 13:38 UTC, connorpgpmcelroy requested changes
Minor change requested

2024-01-23 13:38 UTC, connorpgpmcelroy commented on src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.ts
> +import { ScreenNavigationModel } from 'api/hearings/models/screenNavigation.model';
Should not have references to src, should be '../'. Also, preferably should not be using api/ but not present in src then not as necessary

2024-01-24 12:19 UTC, RiteshHMCTS submitted a review, later dismissed

2024-01-29 14:35 UTC, richardhenryash approved these changes

2024-01-29 15:34 UTC, olusegz07 approved these changes

2024-01-29 15:52 UTC, connorpgpmcelroy submitted a review, later dismissed
Import ordering is still not correct but minor issue. Will approve

2024-01-30 10:01 UTC, andywilkinshmcts requested changes
Change the function getScreenFlowFrom Store to be properly async
Handle all the screens - statically declare a mapping from screen

2024-01-31 10:11 UTC, andywilkinshmcts commented on src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.ts
> +  public getScreenFlowFromStore(hearingStore) {
declare return type

2024-02-07 10:17 UTC, connorpgpmcelroy approved these changes
Approved with minor comment

2024-02-07 10:17 UTC, connorpgpmcelroy commented on src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.ts
> +import { Observable } from 'rxjs';
Imports should be ordered '@...', 'a-z...', '../../../..', '../', ./' ideally

2024-02-07 10:51 UTC, kasi-subramaniam approved these changes

2024-02-09 09:50 UTC, andywilkinshmcts requested changes
I think we need some more tests as suggested, and to check the toolkit version

2024-02-09 09:50 UTC, andywilkinshmcts commented on yarn.lock
> +    "@hmcts/ccd-case-ui-toolkit": 7.0.8-compress-ls
This is probably not the version of toolkit you want. The live version is 7.0.10

2024-02-09 09:50 UTC, andywilkinshmcts commented on src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.spec.ts
> +    it('should call removeUnnecessarySummaryTemplateItems in ngOnInit', () => {
I really think you need a test that actually tests the functionality.  Refactor to make the template and screen flow constructor parameters (with defaults). 
Define a mock template, and mock screen flow, and pass these to the component under test. Check that the expected items are removed and that no unexpected items are removed

2024-02-12 09:47 UTC, andywilkinshmcts approved these changes
Don't change the toolkit version - other than that v good

2024-02-12 09:47 UTC, andywilkinshmcts commented on package.json
> +    "@hmcts/ccd-case-ui-toolkit": "7.0.8-compress-ls",
Don't change the toolkit version

2024-02-12 09:57 UTC, RiteshHMCTS commented on package.json
> +    "@hmcts/ccd-case-ui-toolkit": "7.0.8-compress-ls",
@OgunyemiO can you revert the TL version if you have not done any toolkit changes

2024-02-13 15:43 UTC, connorpgpmcelroy commented on src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.ts
> +import { Observable } from 'rxjs';
minor issue but still not the case

2024-02-13 15:59 UTC, HYadavHMCTS approved these changes

2024-02-13 16:11 UTC, connorpgpmcelroy approved these changes

2024-02-15 11:05 UTC, merged