Bug/EUI 9158
hmcts/rpx-xui-webapp pull request #3501
Opened 2024-01-26 15:23 UTC by DavidJayakumar

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/EUI-9158

### Change description ###

Fix additional facilities label issue
 
### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2024-01-29 10:06 UTC, johnbenjamin-hmcts approved these changes

2024-01-29 11:08 UTC, Daniel-Lam requested changes
@DavidJayakumar - minor spelling issue but otherwise OK

2024-01-29 11:08 UTC, Daniel-Lam commented on src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.html
> +      <exui-amendment-label *ngIf="showAmmended" [displayLabel]="amendmentLabelEnum.AMENDED">
@DavidJayakumar - "amended" has just one "m"

2024-01-29 11:08 UTC, Daniel-Lam commented on src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.html
> +          <exui-amendment-label *ngIf="showAmmendedForFacilitiesRequired(additionalFacility)" [displayLabel]="amendmentLabelEnum.AMENDED">
@DavidJayakumar - "amended" has just one "m"

2024-01-29 11:08 UTC, Daniel-Lam commented on src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.ts
> +  public showAmmended: boolean;
@DavidJayakumar - "amended" has just one "m"

2024-01-29 11:08 UTC, Daniel-Lam commented on src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.ts
> +      this.showAmmended = !_.isEqual(objA, objB);
@DavidJayakumar - "amended" has just one "m"

2024-01-30 13:02 UTC, Daniel-Lam requested changes
@DavidJayakumar - you missed two corrections

2024-01-30 13:02 UTC, Daniel-Lam commented on src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.html
> +          <exui-amendment-label *ngIf="showAmmendedForFacilitiesRequired(additionalFacility)" [displayLabel]="amendmentLabelEnum.AMENDED">
@DavidJayakumar - still not corrected: `showAmmendedForFacilitiesRequired`

2024-01-30 13:02 UTC, Daniel-Lam commented on src/hearings/containers/request-hearing/hearing-edit-summary/additional-facilities-section/additional-facilities-section.component.ts
> +  public showAmmendedForFacilitiesRequired(facility: string): boolean {
@DavidJayakumar - still not corrected: `showAmmendedForFacilitiesRequired`

2024-01-30 14:08 UTC, Daniel-Lam requested changes
@DavidJayakumar - another observation on the newly added spec file

2024-01-30 14:08 UTC, Daniel-Lam commented on src/hearings/containers/request-hearing/hearing-edit-summary/judge-details-section/judge-details-section.component.spec.ts
> +    expect(component.showAmmendedForNeedJudge).toEqual(false);
@DavidJayakumar - same spelling error here (double "m")... looks like this change is new because I didn't see it before

2024-02-09 09:39 UTC, udaydenduluri33 approved these changes

2024-02-13 17:15 UTC, merged