fix COT-790
hmcts/rpx-xui-webapp pull request #3556
Opened 2024-02-27 15:19 UTC by shahedhmcts

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/COT-790

### Change description ###

### Checklist

- [x ] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2024-02-27 15:27 UTC, andywilkinshmcts requested changes

2024-02-27 15:27 UTC, andywilkinshmcts commented on src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
> -          reasonableAdjustments: this.getAllPartyFlagsByPartyId(partyDetail.partyID)
We don't need any business logic, should be fine to just write
reasonableAdjustments: partyDetail.?individualdetails.?reasonableAdjustments

2024-03-01 14:45 UTC, andywilkinshmcts approved these changes
Probably needs further refactoring because I don't think that combinePartiesWithIndOrOrg is actually doing anything any longer

2024-03-01 16:38 UTC, olusegz07 approved these changes

2024-03-04 10:43 UTC, merged