EXUI-1729: Validation error messages added for Hearing location
hmcts/rpx-xui-webapp pull request #3624
Opened 2024-04-03 10:43 UTC by SomeshRA

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/EXUI-1729

### Change description ###
Validation error messages added for Hearing location

### Checklist

- [x ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-04-03 13:37 UTC, RiteshHMCTS approved these changes

2024-04-03 14:22 UTC, SomeshRA commented on package.json
> +    "@hmcts/rpx-xui-common-lib": "v2.0.17-search-venue-fix",
@RiteshHMCTS this was suggested by @andywilkinshmcts

2024-04-04 10:56 UTC, andywilkinshmcts requested changes
Please update the version number for your pre-release

2024-04-04 10:56 UTC, andywilkinshmcts commented on package.json
> +    "@hmcts/rpx-xui-common-lib": "v2.0.17-search-venue-fix",
Some understandable confusion. The tag has v at the start, but the version number itself should not. Unfortunately you'll have to do another pre-release with tag "v2.0.17-search-venue-fix-2" but version number "2.0.17-search-venue-fix"

2024-04-08 09:49 UTC, connorpgpmcelroy submitted a review, later dismissed
LGTM

2024-04-08 10:10 UTC, RiteshHMCTS approved these changes

2024-06-20 13:26 UTC, merged