chart yaml version number changed
hmcts/rpx-xui-webapp pull request #3635
Opened 2024-04-10 12:01 UTC by OgunyemiO

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/EXUI-1719

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-04-10 13:07 UTC, Josh-HMCTS submitted a review, later dismissed

2024-04-11 09:22 UTC, andywilkinshmcts requested changes
Should be 3.1.0

2024-04-11 09:27 UTC, andywilkinshmcts approved these changes

2024-04-11 09:35 UTC, olusegz07 approved these changes

2024-04-15 17:08 UTC, merged