EXUI-1750: Prevent submission if there are no updates
hmcts/rpx-xui-webapp pull request #3636
Opened 2024-04-11 12:01 UTC by SomeshRA

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/EXUI-1750

### Change description ###
Prevent submission if there are no updates

### Checklist

- [X] tests have been updated / new tests has been added (if needed)
- [X ] Does this PR introduce a breaking change

2024-04-12 10:52 UTC, andywilkinshmcts requested changes

2024-04-12 10:52 UTC, andywilkinshmcts commented on src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
> +      JSON.parse(JSON.stringify(hearingRequestMainModel, this.replacer)),
The idea here seems to be to extract all the partyName values. This is not obvious - took me a few mins to figure it out. 
This seems like quite a big change to the way that the feature works. Previously it was comparing the whole object, now it nulls out all the values except partyName.

Is this really what is wanted. If so I suggest that you add a comment explaining why and how this works.

2024-04-15 14:16 UTC, andywilkinshmcts approved these changes

2024-04-16 10:03 UTC, RiteshHMCTS approved these changes

2024-04-17 10:25 UTC, andywilkinshmcts approved these changes

2024-04-19 10:46 UTC, merged