Exui-1779: Making Language Interpreter inactive
hmcts/rpx-xui-webapp pull request #3639
Opened 2024-04-16 17:04 UTC by SomeshRA

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/EXUI-1779

### Change description ###
Making Language Interpreter inactive

### Checklist

- [ x] tests have been updated / new tests has been added (if needed)

2024-04-17 10:37 UTC, andywilkinshmcts requested changes
Minor change to test data as noted

2024-04-17 10:37 UTC, andywilkinshmcts commented on src/hearings/hearing.test.data.ts
> +              interpreterLanguage: 'sat',
Please change to a valid lang code

2024-04-17 10:53 UTC, OgunyemiO approved these changes

2024-04-19 09:42 UTC, andywilkinshmcts approved these changes

2024-04-24 10:05 UTC, merged