Bug/e UI 2028 tasks not being unassigned
hmcts/rpx-xui-webapp pull request #3794
Opened 2024-07-10 12:59 UTC by connorpgpmcelroy

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/EXUI-2028

### Change description ###
Make the API calls to get caseworkers on node layer when starting up to stop loading issues

2024-07-12 14:11 UTC, RiteshHMCTS approved these changes

2024-07-16 14:15 UTC, andywilkinshmcts requested changes

2024-07-17 10:38 UTC, connorpgpmcelroy commented on api/workAllocation/caseWorkerService.ts
> +    logger.warn('Case workers now returning MAX_RECORDS', response.data.roleAssignmentResponse.length);
Created ticket https://tools.hmcts.net/jira/browse/EXUI-2111 for this

2024-07-18 08:58 UTC, RiteshHMCTS approved these changes

2024-07-18 11:32 UTC, andywilkinshmcts approved these changes

2024-07-22 10:31 UTC, merged