EXUI_2193: Local mc-menu-item config
hmcts/rpx-xui-webapp pull request #3833
Opened 2024-08-09 16:02 UTC by Josh-HMCTS

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/EXUI-2193

### Change description ###

Move mc-menu-items out of LD

2024-09-26 14:27 UTC, andywilkinshmcts requested changes
this looks like it will work, but you might have missed an opportunity with the various environment configs
I think they should all be defined in terms of the prod config, something like

aatConfig = {
  ...prodConfig,
  // differences only go here
 }
  
This should be easier to maintain, though in some cases it's a bit fiddly
Can you see if it's practical to capture the differences between AAT and Prod in this way?

2024-10-02 11:03 UTC, andywilkinshmcts reviewed
I like it. Quite clear what is what

2024-10-02 11:03 UTC, andywilkinshmcts commented on api/configuration/menuConfigs/configs.ts
> +    const rolesRegexChanges = {
This bit is just a screw up really. It should be (judge)|(judiciary)|(panelmember) in all configs
    }

2024-10-02 11:03 UTC, andywilkinshmcts commented on api/configuration/menuConfigs/configs.ts
> +    const rolesRegexChanges = {
You can leave it for now if you like, or if you want to you can just eliminate that difference

2024-10-02 11:04 UTC, andywilkinshmcts approved these changes, later dismissed

2024-10-03 09:50 UTC, RiteshHMCTS approved these changes, later dismissed

2024-10-16 10:06 UTC, Josh-HMCTS commented
This has been merged in to the SRT branch

2026-07-14 11:34 UTC, closed without merging