EXUI-2277 - Move mc-menu-theme out of LD
hmcts/rpx-xui-webapp pull request #3850
Opened 2024-08-22 13:03 UTC by Josh-HMCTS

### Jira link

See [EXUI-2277](https://tools.hmcts.net/jira/browse/EXUI-2277)

### Change description

Move the mc-menu-theme out of launch darkly and in to angular config

2024-08-23 12:29 UTC, andywilkinshmcts requested changes

2024-08-23 12:29 UTC, andywilkinshmcts commented on src/app/containers/app-header/app-header.component.ts
> +      theme !== 'default' && theme.split('|').some((role) => userRolesSet.has(role))
Can you make the role matching for themes a regex please. What you've done works, but isn't functionally equivalent to what we had. You should also change default to '.+'
Then you could do something like 
const userTheme = Object.keys(availableThemes.some((themeRegex) => userRolesSet.some((role) => role.matches(themeRegex)))

2024-08-27 08:29 UTC, StoneBenHMCTS submitted a review, later dismissed

2024-08-27 09:53 UTC, andywilkinshmcts submitted a review, later dismissed
Thanks - looks good

2024-09-02 10:28 UTC, RiteshHMCTS approved these changes

2024-09-02 10:38 UTC, andywilkinshmcts approved these changes

2024-09-02 11:00 UTC, merged