COT-900 - Date validation enhancement on hearing timing
hmcts/rpx-xui-webapp pull request #3972
Opened 2024-10-22 11:39 UTC by anthonydummer

### Jira link

https://tools.hmcts.net/jira/browse/COT-900

### Change description

### Testing done

I have tested a range of valid and invalid dates in all the affected date fields to confirm that invalid dates, including partially input dates are correctly identified and errors output.  Existing validation for other date checks also continue to work. 

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2024-10-22 13:20 UTC, RiteshHMCTS approved these changes

2024-10-22 13:35 UTC, StoneBenHMCTS submitted a review, later dismissed

2025-02-03 09:55 UTC, RiteshHMCTS submitted a review, later dismissed

2025-02-03 16:48 UTC, connorpgpmcelroy requested changes
Minor changes requested

2025-02-03 16:48 UTC, connorpgpmcelroy commented on src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
> +      console.log('One or more form controls are missing.');
This log needed now?

2025-02-03 16:48 UTC, connorpgpmcelroy commented on src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
> +      if ((this?.earliestDateOfHearingError && this?.earliestDateOfHearingError.isInvalid) && (this?.latestDateOfHearingError && this?.latestDateOfHearingError.isInvalid)) {
Unsure if relevant but is 'this?' needed with the optional chaining?

2025-02-03 16:48 UTC, connorpgpmcelroy commented on src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
> +          message: HearingDatePriorityEnum.InValidHearingDateError
InValid capitalisation not consistent with '.isInvalid'. All instances of this should be consistent with Invalid casing

2025-02-04 10:17 UTC, andywilkinshmcts approved these changes
address Connor's minor comment

2025-02-04 10:17 UTC, andywilkinshmcts commented on src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
> +    const monthControl = formGroup.get(`${id}_month`);
As part of Ben's accessibility work you may find that these Id's change. Fine for now

2025-02-04 10:17 UTC, andywilkinshmcts commented on src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
> +      if ((this?.earliestDateOfHearingError && this?.earliestDateOfHearingError.isInvalid) && (this?.latestDateOfHearingError && this?.latestDateOfHearingError.isInvalid)) {
It's not needed - if you have no this something is badly wrong

2025-02-04 10:17 UTC, andywilkinshmcts commented on src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
> +          message: HearingDatePriorityEnum.InValidHearingDateError
that's a valid comment

2025-02-04 11:30 UTC, anthonydummer commented on src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
> +      if ((this?.earliestDateOfHearingError && this?.earliestDateOfHearingError.isInvalid) && (this?.latestDateOfHearingError && this?.latestDateOfHearingError.isInvalid)) {
Thank you for the spot, removed now.

2025-02-04 11:30 UTC, anthonydummer commented on src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
> +          message: HearingDatePriorityEnum.InValidHearingDateError
Thank you, updated now

2025-02-04 11:36 UTC, andywilkinshmcts submitted a review, later dismissed

2025-02-04 12:50 UTC, connorpgpmcelroy approved these changes
LGTM

2025-02-10 15:58 UTC, Josh-HMCTS approved these changes

2025-02-10 16:16 UTC, merged