Query Management Playwright E2E
hmcts/rpx-xui-webapp pull request #3976
Opened 2024-10-24 13:46 UTC by kasi-subramaniam

Query Management Playwright E2E

2024-11-05 12:20 UTC, andywilkinshmcts requested changes
Basically very good, a few fairly picky changes requested. The only one you really need to address is to make the hearing date tomorrow's date.

2024-11-05 12:20 UTC, andywilkinshmcts commented on playwright_tests/E2E/query-mgmt.test.ts
> +    caseId = '1730145870311253'; //
The test should ideally create its own case. Otherwise we have to scramble round and recreate test cases when old data gets cleaned up

2024-11-05 12:20 UTC, andywilkinshmcts commented on playwright_tests/config.ts
> +const queryMgmtURL = process.env.QM_BASE_URL || "https://xui-fpl-case-service-pr-5582.preview.platform.hmcts.net";
This is obviously only temporary

2024-11-05 12:20 UTC, andywilkinshmcts commented on playwright_tests/E2E/helpers/base-page.ts
> +  getCurrentDate():string {
if you really need that format, then maybe date.toLocalDateString.split('/').join(' ');

2024-11-10 16:07 UTC, kasi-subramaniam commented on playwright.config.ts
> +//export const axeTestEnabled = process.env.ENABLE_AXE_TESTS === 'true';
this has been uncommented

2024-11-10 16:07 UTC, kasi-subramaniam commented on playwright_tests/E2E/fixtures/create-fixture.ts
> +type CreateFixture = {
changed to query-management-fixture.ts

2024-11-10 16:09 UTC, kasi-subramaniam commented on playwright_tests/E2E/helpers/base-page.ts
> +  getCurrentDate():string {
getCurrentDate() is actually not being used anywhere - hence I have removed it

2024-11-10 16:13 UTC, kasi-subramaniam commented on playwright_tests/E2E/pages/manage-documents.ts
> +    await this.page.waitForTimeout(3000);
second waitForTimeout() has now been removed.

2024-11-10 16:28 UTC, kasi-subramaniam commented on playwright_tests/E2E/pages/raise-query.ts
> +    const xuiQMLandingUrl = config.QMBaseURL + '/case-details/' + caseId + '#Query%20Management';
done

2024-11-10 16:28 UTC, kasi-subramaniam commented on playwright_tests/E2E/pages/raise-query.ts
> +    await this.page.getByText('Query Management').click();
done

2024-11-10 16:31 UTC, kasi-subramaniam commented on playwright_tests/E2E/pages/raise-query.ts
> +    await this.page.waitForTimeout(5000);
comment removed.

2026-06-22 20:00 UTC, closed without merging