Add ability to set CCD/RAS url when talking to HMC
hmcts/rpx-xui-webapp pull request #3979
Opened 2024-10-24 16:28 UTC by linusnorton

2025-02-13 16:21 UTC, andywilkinshmcts requested changes
Not quite ready for prime time

2025-02-13 16:21 UTC, andywilkinshmcts commented on api/hearings/hmc.index.ts
> +  console.log('injectHearingsHeaders');
Please remove the console.log

2025-02-13 16:21 UTC, andywilkinshmcts commented on api/hearings/hmc.index.ts
> +    console.log('injectHearingsHeaders', req.headers);
Please remove the console.log

2025-02-13 16:21 UTC, andywilkinshmcts commented on config/custom-environment-variables.json
> +      "enablePreviewCcd": "ENABLE_HMC_PREVIEW_CCD"
Naming things is one of the hard problems, but can we call this something else, because it's not specific to preview, hearings or CCD. I'd suggest enableDataSourceHeaders, with corresponding changes in the environment variable name too

2025-02-13 16:21 UTC, andywilkinshmcts commented on src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
> +      expect(tabs.length).not.toEqual(0)
The test no longer tests the thing it is supposed to test. We need to understand why

2025-02-13 16:21 UTC, andywilkinshmcts commented on src/cases/containers/case-viewer-container/case-viewer-container.component.ts
> +        return this.appendedTabs;
You can't do this unfortunately - you'll break the functionality

2025-02-13 16:21 UTC, andywilkinshmcts commented on src/hearings/services/hearings-feature.service.ts
> +        console.log(featureVariations);
Please undo these changes

2025-02-13 17:05 UTC, andywilkinshmcts submitted a review, later dismissed

2025-02-14 09:33 UTC, RiteshHMCTS submitted a review, later dismissed
LGTM

2025-03-11 14:17 UTC, Josh-HMCTS approved these changes
Prior approvals

2025-03-11 14:18 UTC, merged