Add changes and relevant tests
hmcts/rpx-xui-webapp pull request #4097
Opened 2024-11-05 15:46 UTC by connorpgpmcelroy

### Jira link

https://tools.hmcts.net/jira/browse/EXUI-2352

### Change description

Ensure roles without jurisdiction assigned can affect the role category

### Testing done

Ensure get all roles back relevant to the payload without jurisdiction in payload. Also added tests to ensure this will not affect the role category usage.

2024-11-06 09:43 UTC, andywilkinshmcts requested changes

2024-11-06 09:43 UTC, andywilkinshmcts commented on api/workAllocation/util.ts
> +    (!roleAssign.attributes?.jurisdiction || services.includes(roleAssign.attributes.jurisdiction))
Should also check that the roleAssign has a category - don't want to end up returning one without a category
e.g roleAssign.roleCategory && (!roleAssign.attributes?.jurisdiction || services.includes(roleAssign.attributes.jurisdiction))

2024-11-12 12:13 UTC, andywilkinshmcts approved these changes

2024-11-13 09:37 UTC, RiteshHMCTS approved these changes

2025-01-13 14:43 UTC, merged