Release/a11y fixes
hmcts/rpx-xui-webapp pull request #944
Opened 2021-03-10 13:09 UTC by ronaldmansveld

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-03-17 10:34 UTC, paul-graham requested changes
I'm assuming the `package.json` will be updated to point at a fully released version of the toolkit before this gets merged. I've reviewed the other changes and I see no issues at all... but just to play it safe, I'm going to reserve my "Approve" until it's pointing at the released version. :)

2021-04-30 09:28 UTC, paul-graham commented on src/app/app.module.ts
> +// APP store
_Nitpick:_
This comment and the one above is no longer relevant, following the reordering of the imports.

2021-04-30 09:30 UTC, paul-graham submitted a review, later dismissed
The `package.json` concern is no more. Just a couple of comments around the imports in `app.module.ts` that are no longer relevant but that's certainly not enough to stop approval. 👍

2021-04-30 09:38 UTC, Mo-Lala84 submitted a review, later dismissed
approved

2021-05-17 10:47 UTC, paul-graham approved these changes

2021-05-17 10:53 UTC, Mo-Lala84 submitted a review, later dismissed
approved

2021-06-14 16:41 UTC, Mo-Lala84 approved these changes
approved

2021-06-14 16:43 UTC, udaydenduluri33 submitted a review, later dismissed
LGTMm

2021-06-14 17:38 UTC, rayliangatos submitted a review, later dismissed

2021-06-30 12:04 UTC, Mo-Lala84 approved these changes
approved

2021-06-30 12:09 UTC, udaydenduluri33 approved these changes
LGTMm

2021-07-01 10:00 UTC, merged